DATA_PORT: 10000
HELLO_PORT: 5000

MYSQL:
  TABLE_NAME: 'Bundles'
  DATABASE_NAME: 'sdtn'
  USER: 'sdtn'
  PASSWORD: 'password'
  COLUMNS: ['type', 'seq', 'sid', 'payload', 'averageData', 'minData', 'maxData', 'action']

MAX_ACK_TIMEOUT: 5
WIRELESS_INTERFACE: 'wlan0'

MAX_DATA_ENTRIES: 50
DROPPING_PROTOCOL: 0
DATA_TO_BUNDLE_SIZE: 5

DATA_GENERATED_SIZE: 1
TIME_TO_GENERATE_DATA: 1

SENSOR_ID: 1