DATA_PORT: 10000
HELLO_PORT: 5000

MYSQL:
  TABLE_NAME: 'sensor_data'
  DATABASE_NAME: 'sdtn'
  USER: 'sdtn'
  PASSWORD: 'thesisit'
  COLUMNS: ['timestamp', 'seq_number', 'data']

MAX_ACK_TIMEOUT: 5
WIRELESS_INTERFACE: 'wlp2s0'

MAX_DATA_ENTRIES: 50
DROPPING_PROTOCOL: 0
DATA_TO_BUNDLE_SIZE: 5

DATA_GENERATED_SIZE: 1
TIME_TO_GENERATE_DATA: 1

SENSOR_ID: 1